from .user_routes import users
from .auth_routes import auth
from .temple_routes import temples
from .species_routes import species
from .master_routes import masters
from .padawan_routes import padawans
from .lightsaber_routes import lightsabers
from .crystal_routes import crystals
from .course_routes import courses
from .padawan_course_routes import enrollments
